CREATE TABLE ISSUES (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username varchar(255) not null,
	repository varchar(255) not null
);

insert into ISSUES (username, repository) values ('marcingrzejszczak', 'spring-cloud/spring-cloud-sleuth');